id = "angular"
name = "Angular"
description = "Angular Language support"
version = "0.0.1"
schema_version = 1
authors = ["nathansbradshaw"]
repository = "https://github.com/nathansbradshaw/zed-angular"
path_suffixes = ["html", "ng.html"]

[language_servers.angular]
name = "Angular Language Server"
language = "Angular"
language_ids = { "Angular" = "angular" }

[grammars.angular]
repository = "https://github.com/dlvandenberg/tree-sitter-angular"
commit = "cba288924f4832abb619c627539f111004ff22e5"
