name = "Angular"
grammar = "angular"
path_suffixes = ["component.html", "ng.html"]
block_comment = ["<!-- ", " -->"]
autoclose_before = ";:.,=}])>\"'"
prettier_parser_name = "angular"

scope_opt_in_language_servers = ["tailwindcss-language-server"]

# Define brackets for TypeScript, HTML, CSS, and SCSS with Angular specific extensions
brackets = [
    # TypeScript and Angular script sections in components
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = false },
    { start = "(", end = ")", close = true, newline = false },
    { start = "<", end = ">", close = false, newline = true, not_in = [
        "string",
        "comment",
    ] },
    { start = "\"", end = "\"", close = true, newline = false, not_in = [
        "string",
    ] },
    { start = "'", end = "'", close = true, newline = false, not_in = [
        "string",
    ] },
    { start = "`", end = "`", close = true, newline = false, not_in = [
        "string",
    ] },
]

# Integration with other tools
linting = ["eslint", "codelyzer"]
formatting = ["prettier"]

# Real-time features
real_time_syntax_checking = true
real_time_semantic_checking = true
code_lens_features = ["references", "tests"]

# Documentation and tooltips
documentation = true
hover_information = true

# Plugin and extension support
plugin_support = true
